#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package install ag <args...>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  which ag >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    local package_name="the_silver_searcher"
    if [ "$(os::is_macos)" = "true" ]; then
      package_name="the_silver_searcher"
    elif [ "$(os::is_ubuntu)" = "true" ]; then
      package_name="silversearcher-ag"
    fi

    pm install -y $package_name
  fi

  log::success "install ag success."
}

run() {
  core $@
}

run $@
